/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 08 23:56:42 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DoubleLinkedList_ESTest extends DoubleLinkedList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.clear();
      doubleLinkedList0.addLast("");
      doubleLinkedList0.indexOf((Object) null);
      doubleLinkedList0.getLast();
      Object[] objectArray0 = doubleLinkedList0.toArray();
      doubleLinkedList0.toArray(objectArray0);
      // Undeclared exception!
      try { 
        doubleLinkedList0.remove((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1, Size: 1
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Collection<Integer> collection0 = null;
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.indexOf((Object) null);
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.lastIndexOf((Object) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[4];
      objectArray0[0] = (Object) doubleLinkedList0;
      objectArray0[2] = (Object) doubleLinkedList0;
      doubleLinkedList0.clear();
      objectArray0[3] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.addLast(objectArray0[0]);
      doubleLinkedList0.contains(objectArray0[3]);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = 618;
      String string0 = null;
      doubleLinkedList0.addFirst((Object) null);
      doubleLinkedList0.repOK();
      // Undeclared exception!
      try { 
        doubleLinkedList0.addAll((Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[3];
      objectArray0[1] = (Object) doubleLinkedList0;
      objectArray0[2] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.clear();
      doubleLinkedList0.toArray(objectArray0);
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator((-4));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -4, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      String string0 = null;
      doubleLinkedList0.add((Object) null);
      doubleLinkedList0.getLast();
      int int0 = 0;
      doubleLinkedList0.remove(0);
      doubleLinkedList0.addFirst((Object) null);
      // Undeclared exception!
      try { 
        doubleLinkedList0.clone();
        fail("Expecting exception: InternalError");
      
      } catch(InternalError e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.clear();
      // Undeclared exception!
      try { 
        doubleLinkedList0.getFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      String string0 = "\\%}y^i9KBqo}$";
      doubleLinkedList0.addFirst("%}y^i9KBqo}$");
      doubleLinkedList0.clear();
      doubleLinkedList0.repOK();
      int int0 = (-3350);
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.size();
      int int0 = 1;
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) doubleLinkedList0;
      objectArray0[1] = (Object) doubleLinkedList0;
      doubleLinkedList0.modCount = 0;
      // Undeclared exception!
      try { 
        doubleLinkedList0.test((DoubleLinkedList) null, objectArray0[0]);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      int int0 = 0;
      doubleLinkedList0.test(doubleLinkedList1, doubleLinkedList1);
      doubleLinkedList1.modCount = 0;
      doubleLinkedList0.contains(doubleLinkedList1);
      doubleLinkedList1.modCount = 1063;
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator(1063);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1063, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) doubleLinkedList0;
      doubleLinkedList0.toArray(objectArray0);
      doubleLinkedList0.listIterator(0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.addLast((Object) null);
      doubleLinkedList0.lastIndexOf((Object) null);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object object0 = null;
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = null;
      objectArray0[1] = null;
      objectArray0[2] = null;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.remove((Object) null);
      Object[] objectArray1 = new Object[5];
      doubleLinkedList0.containsAllInOrder(objectArray1);
      // Undeclared exception!
      try { 
        doubleLinkedList0.remove((-4749));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -4749, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = (-2432);
      // Undeclared exception!
      try { 
        doubleLinkedList0.toArray((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      doubleLinkedList0.indexOf(doubleLinkedList1);
      // Undeclared exception!
      try { 
        doubleLinkedList1.addAll((Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.contains((Object) null);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.add(1, (Object) "no~Q~I9)m31g J{nI");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator(144);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 144, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.addLast((Object) null);
      doubleLinkedList0.remove(0);
      doubleLinkedList0.add(0, (Object) null);
      doubleLinkedList0.get(0);
      doubleLinkedList0.add(0, (Object) null);
      doubleLinkedList0.addLast((Object) null);
      doubleLinkedList0.removeFirst();
      doubleLinkedList0.removeFirst();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.addLast("");
      doubleLinkedList0.getFirst();
      int int0 = 0;
      doubleLinkedList0.removeFirst();
      // Undeclared exception!
      try { 
        doubleLinkedList0.clone();
        fail("Expecting exception: InternalError");
      
      } catch(InternalError e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.size();
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      doubleLinkedList0.addFirst(doubleLinkedList1);
      doubleLinkedList1.remove((Object) doubleLinkedList0);
      doubleLinkedList0.add(0, (Object) doubleLinkedList1);
      doubleLinkedList0.removeLast();
      Object object0 = doubleLinkedList0.removeFirst();
      doubleLinkedList1.remove(object0);
      // Undeclared exception!
      try { 
        doubleLinkedList1.removeFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      doubleLinkedList1.modCount = 145;
      DoubleLinkedList doubleLinkedList2 = new DoubleLinkedList();
      doubleLinkedList1.addLast(doubleLinkedList2);
      doubleLinkedList1.remove(0);
      // Undeclared exception!
      try { 
        doubleLinkedList0.set(145, doubleLinkedList1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 145, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.set((-1774), "9.KIx92nJXeNl+");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1774, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Collection<Object> collection0 = null;
      // Undeclared exception!
      try { 
        doubleLinkedList0.addAll(1, (Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.modCount = (-1);
      // Undeclared exception!
      try { 
        doubleLinkedList0.remove(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[2];
      Object[] objectArray1 = new Object[0];
      doubleLinkedList0.toArray(objectArray1);
      objectArray0[0] = (Object) doubleLinkedList0;
      objectArray0[1] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.listIterator(0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.get(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.getLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.listIterator(0);
      doubleLinkedList0.size();
      doubleLinkedList0.clear();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.getLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = 0;
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList1.removeFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.toArray();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = (-3004);
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator((-3004));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -3004, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.get((-2512));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -2512, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      doubleLinkedList0.add((Object) doubleLinkedList1);
      doubleLinkedList0.modCount = 21;
      int int0 = (-1479);
      Collection<String> collection0 = null;
      DoubleLinkedList doubleLinkedList2 = null;
      try {
        doubleLinkedList2 = new DoubleLinkedList((Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Collection<DoubleLinkedList> collection0 = null;
      // Undeclared exception!
      try { 
        doubleLinkedList0.addAll((Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = 1;
      // Undeclared exception!
      try { 
        doubleLinkedList0.remove(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.clone();
        fail("Expecting exception: InternalError");
      
      } catch(InternalError e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.get(3371);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 3371, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.modCount = 0;
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      doubleLinkedList1.remove((Object) doubleLinkedList0);
      doubleLinkedList0.add((Object) doubleLinkedList1);
      doubleLinkedList0.getLast();
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1, Size: 1
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.clone();
        fail("Expecting exception: InternalError");
      
      } catch(InternalError e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[1];
      objectArray0[0] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      // Undeclared exception!
      try { 
        doubleLinkedList0.add((-661), (Object) "");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -661, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.repOK();
      doubleLinkedList0.remove((Object) "");
      // Undeclared exception!
      try { 
        doubleLinkedList0.getFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = (-777);
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) doubleLinkedList0;
      objectArray0[1] = (Object) doubleLinkedList0;
      objectArray0[2] = (Object) doubleLinkedList0;
      doubleLinkedList0.containsAllInOrder(objectArray0);
      doubleLinkedList0.remove(objectArray0[2]);
      int int1 = (-23);
      doubleLinkedList0.modCount = (-23);
      // Undeclared exception!
      try { 
        doubleLinkedList0.getLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) doubleLinkedList0;
      objectArray0[1] = (Object) doubleLinkedList0;
      // Undeclared exception!
      try { 
        doubleLinkedList0.add(2748, (Object) "Z6Zp{2");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2748, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      int int0 = 0;
      int int1 = (-4893);
      doubleLinkedList0.modCount = (-4893);
      // Undeclared exception!
      try { 
        doubleLinkedList0.getLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.repOK();
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator((-888));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -888, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Collection<Object> collection0 = null;
      DoubleLinkedList doubleLinkedList0 = null;
      try {
        doubleLinkedList0 = new DoubleLinkedList((Collection) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.clear();
      doubleLinkedList0.remove((Object) "");
      doubleLinkedList0.addLast("");
      doubleLinkedList0.indexOf("");
      doubleLinkedList0.getLast();
      Object[] objectArray0 = doubleLinkedList0.toArray();
      doubleLinkedList0.toArray(objectArray0);
      doubleLinkedList0.remove(0);
      // Undeclared exception!
      try { 
        doubleLinkedList0.removeLast();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.listIterator((-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1, Size: 0
         //
         verifyException("DoubleLinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.lastIndexOf("Index: ");
      DoubleLinkedList doubleLinkedList1 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.getFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      // Undeclared exception!
      try { 
        doubleLinkedList0.remove((-1504));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1504, Size: 0
         //
         verifyException("DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = new DoubleLinkedList();
      doubleLinkedList0.addFirst("%}y^i9KBqo}$");
      doubleLinkedList0.clear();
      // Undeclared exception!
      try { 
        doubleLinkedList0.getFirst();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("DoubleLinkedList", e);
      }
  }
}
