/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 00:16:16 GMT 2021
 */

package orig;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import orig.DisjSets;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DisjSets_ESTest extends DisjSets_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(0);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "|QZ:";
      stringArray0[1] = "";
      stringArray0[2] = "[_";
      stringArray0[3] = "";
      stringArray0[4] = "0E&";
      stringArray0[5] = "pr'O-";
      stringArray0[6] = "";
      stringArray0[7] = "";
      stringArray0[8] = "";
      DisjSets.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSets0.find(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(0);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "n,";
      stringArray0[1] = "orig.DisjSets";
      stringArray0[2] = "Bh};4";
      stringArray0[3] = "FO?YcS.";
      stringArray0[4] = "f8X4iT>OqK,U Y\"\":M(";
      stringArray0[5] = "";
      stringArray0[6] = "";
      stringArray0[7] = "";
      stringArray0[8] = "";
      DisjSets.main(stringArray0);
      DisjSets.main((String[]) null);
      // Undeclared exception!
      try { 
        disjSets0.find(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String string0 = ";4^&pRvP";
      stringArray0[0] = ";4^&pRvP";
      DisjSets.main(stringArray0);
      DisjSets disjSets0 = new DisjSets(70);
      DisjSets.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSets0.union(128, 70);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 70
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(128);
      String[] stringArray0 = new String[0];
      DisjSets.main(stringArray0);
      DisjSets.main(stringArray0);
      String[] stringArray1 = new String[3];
      stringArray1[0] = "=3cg{2$eU}nEJykH";
      DisjSets.main(stringArray0);
      DisjSets.main(stringArray1);
      DisjSets.main(stringArray1);
      stringArray1[1] = "";
      String[] stringArray2 = new String[5];
      stringArray2[0] = "";
      stringArray2[1] = "=3cg{2$eU}nEJykH";
      stringArray2[2] = "=3cg{2$eU}nEJykH";
      stringArray2[3] = "";
      stringArray2[4] = "";
      DisjSets.main(stringArray2);
      stringArray1[2] = ";]aQ/q&p`^a";
      DisjSets.main(stringArray1);
      disjSets0.Find(0);
      disjSets0.find(0);
      // Undeclared exception!
      try { 
        disjSets0.union(0, 1710);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[1] = "\"{gYwkx[Il";
      stringArray0[2] = "A{s/|9E]Klz|\"?_?HU";
      stringArray0[3] = "TZ@;xTwX$";
      stringArray0[4] = "Om\"yGNY?6";
      stringArray0[5] = "";
      stringArray0[6] = "pQQo^%1OHS-Y";
      stringArray0[7] = ";MxJMH[,,;>SOgJ";
      stringArray0[8] = "Xh2:D@zQF";
      DisjSets.main(stringArray0);
      DisjSets disjSets0 = new DisjSets(2);
      disjSets0.goodValues();
      DisjSets.main(stringArray0);
      DisjSets.main(stringArray0);
      DisjSets.main(stringArray0);
      disjSets0.find(1);
      disjSets0.find(0);
      DisjSets.main(stringArray0);
      String[] stringArray1 = new String[7];
      stringArray1[0] = ";MxJMH[,,;>SOgJ";
      stringArray1[1] = "pQQo^%1OHS-Y";
      stringArray1[2] = "*8![KKDbd*dd]2<y";
      stringArray1[3] = "";
      stringArray1[4] = "";
      stringArray1[5] = "TZ@;xTwX$";
      stringArray1[6] = ";MxJMH[,,;>SOgJ";
      DisjSets.main(stringArray1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(71);
      disjSets0.acyclic();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DisjSets disjSets0 = null;
      try {
        disjSets0 = new DisjSets((-428));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[5];
      String string0 = "P~&7p[r:oo.{3";
      stringArray0[0] = "P~&7p[r:oo.{3";
      String string1 = " lGy-1$1/p3>";
      stringArray0[1] = " lGy-1$1/p3>";
      String string2 = "@4k,?TSRA0$PQ!?QR(D";
      stringArray0[2] = "@4k,?TSRA0$PQ!?QR(D";
      String string3 = "CLR?Xd2'!Y?";
      stringArray0[3] = "CLR?Xd2'!Y?";
      String string4 = "";
      stringArray0[4] = "";
      DisjSets.main(stringArray0);
      int int0 = 0;
      DisjSets disjSets0 = new DisjSets(0);
      DisjSets.main(stringArray0);
      int int1 = (-1388);
      // Undeclared exception!
      try { 
        disjSets0.union(0, (-1388));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1388
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(0);
      String[] stringArray0 = new String[8];
      String string0 = "9W2.8$kk@\"Q9m?^ksC";
      stringArray0[0] = "9W2.8$kk@\"Q9m?^ksC";
      stringArray0[1] = "PL}Qp`zh]?_gfWZ";
      stringArray0[2] = " M!1G%";
      stringArray0[3] = "~t3Tyf`X*qU}f=JW";
      stringArray0[4] = "y7)/T2";
      DisjSets.main(stringArray0);
      stringArray0[5] = "p";
      stringArray0[6] = "";
      stringArray0[7] = "";
      DisjSets.main(stringArray0);
      int int0 = (-1611);
      // Undeclared exception!
      try { 
        disjSets0.find((-1611));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(0);
      // Undeclared exception!
      try { 
        disjSets0.Find(336);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DisjSets disjSets0 = new DisjSets(2591);
      String[] stringArray0 = new String[7];
      stringArray0[0] = ".c%I!;x";
      stringArray0[1] = "";
      stringArray0[2] = "C>1>MeV.[";
      stringArray0[3] = "";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "}Sr;>Z";
      DisjSets.main(stringArray0);
      disjSets0.goodValues();
      disjSets0.Find(2);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DisjSets.main((String[]) null);
      DisjSets disjSets0 = new DisjSets(0);
      disjSets0.goodValues();
      DisjSets.main((String[]) null);
      // Undeclared exception!
      try { 
        disjSets0.union(2691, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("orig.DisjSets", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = 1788;
      DisjSets disjSets0 = new DisjSets(1788);
      String[] stringArray0 = new String[7];
      DisjSets.main(stringArray0);
      stringArray0[0] = "5~Q";
      stringArray0[1] = "Y|,\" G+";
      stringArray0[2] = "Y_Y>O'>Js~v]=*[jU";
      stringArray0[3] = "";
      DisjSets.main(stringArray0);
      stringArray0[4] = "";
      DisjSets.main(stringArray0);
      DisjSets.main(stringArray0);
      stringArray0[5] = "";
      stringArray0[6] = "";
      DisjSets.main(stringArray0);
      disjSets0.union((-696), 0);
      DisjSets.main(stringArray0);
      disjSets0.Find(0);
      // Undeclared exception!
      try { 
        disjSets0.find((-696));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
