/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 00:15:43 GMT 2021
 */

package fast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import fast.DisjSetsFast;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DisjSetsFast_ESTest extends DisjSetsFast_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = (-242);
      DisjSetsFast disjSetsFast0 = null;
      try {
        disjSetsFast0 = new DisjSetsFast((-242));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fast.DisjSetsFast", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = (-1);
      DisjSetsFast disjSetsFast0 = null;
      try {
        disjSetsFast0 = new DisjSetsFast((-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fast.DisjSetsFast", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(2);
      disjSetsFast0.acyclic();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "EJTvwwpQ(x('.";
      stringArray0[1] = "";
      stringArray0[2] = "h7d|";
      stringArray0[3] = "*";
      stringArray0[4] = "";
      stringArray0[5] = "";
      DisjSetsFast.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSetsFast0.find(2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("fast.DisjSetsFast", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(1674);
      disjSetsFast0.goodValues();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "cUqONGrdcY7&m GgeIr";
      stringArray0[4] = "";
      stringArray0[5] = "2qGijpzj1\"-Fi|qBvw";
      DisjSetsFast.main(stringArray0);
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(399);
      String[] stringArray1 = new String[9];
      stringArray1[0] = "+dsSQYg)+1v8";
      stringArray1[1] = "";
      stringArray1[2] = "C~A%H}ua63;0";
      stringArray1[3] = ";p=TEU[o?i%oHSQz";
      stringArray1[4] = "@_ZoU\"j4<sKpzEA2&K";
      stringArray1[5] = "2qGijpzj1\"-Fi|qBvw";
      stringArray1[6] = "";
      stringArray1[7] = "";
      stringArray1[8] = "2qGijpzj1\"-Fi|qBvw";
      DisjSetsFast.main(stringArray1);
      DisjSetsFast.main(stringArray0);
      DisjSetsFast.main(stringArray0);
      DisjSetsFast.main(stringArray0);
      DisjSetsFast.main(stringArray0);
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.find(0);
      DisjSetsFast.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = (-590);
      DisjSetsFast disjSetsFast0 = null;
      try {
        disjSetsFast0 = new DisjSetsFast((-590));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fast.DisjSetsFast", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(0);
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "rz n/]P(@_";
      stringArray0[2] = "";
      stringArray0[3] = "c.XAHt";
      stringArray0[4] = "MPlY>+\"{v#+&eI$n5";
      DisjSetsFast.main(stringArray0);
      stringArray0[5] = "fast.DisjSetsFast";
      stringArray0[6] = "";
      DisjSetsFast.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSetsFast0.find((-2992));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(223);
      String[] stringArray0 = new String[8];
      stringArray0[0] = "!";
      stringArray0[1] = "";
      DisjSetsFast.main(stringArray0);
      stringArray0[2] = ",#8kwg`VZ";
      stringArray0[3] = "";
      stringArray0[4] = "iS;=5F7<|bH\u0006O";
      stringArray0[5] = "";
      stringArray0[6] = "CKMg{tpz ;D@_iSHN8P";
      stringArray0[7] = "Ag";
      DisjSetsFast.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSetsFast0.find(929);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(128);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "*";
      stringArray0[1] = "dcN";
      stringArray0[2] = "RReMht";
      stringArray0[3] = "";
      stringArray0[4] = "";
      DisjSetsFast.main(stringArray0);
      String[] stringArray1 = new String[3];
      stringArray1[0] = "*";
      stringArray1[1] = "fast.DisjSetsFast";
      stringArray1[2] = "";
      DisjSetsFast.main(stringArray1);
      // Undeclared exception!
      try { 
        disjSetsFast0.Find(128);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[6];
      String string0 = "fast.DisjSetsFast";
      stringArray0[0] = "fast.DisjSetsFast";
      stringArray0[1] = "fast.DisjSetsFast";
      String string1 = "'h+,ya++Y~}=hKc";
      stringArray0[2] = "'h+,ya++Y~}=hKc";
      String string2 = "/~<M{.?^G_@";
      stringArray0[3] = "/~<M{.?^G_@";
      String string3 = "";
      stringArray0[4] = "";
      stringArray0[5] = "M t";
      DisjSetsFast.main(stringArray0);
      int int0 = 0;
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(0);
      DisjSetsFast.main(stringArray0);
      int int1 = 0;
      // Undeclared exception!
      try { 
        disjSetsFast0.Find(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = (-3663);
      DisjSetsFast disjSetsFast0 = null;
      try {
        disjSetsFast0 = new DisjSetsFast((-3663));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("fast.DisjSetsFast", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(1);
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      DisjSetsFast.main(stringArray0);
      DisjSetsFast.main(stringArray0);
      stringArray0[1] = "u!70L9";
      DisjSetsFast.main(stringArray0);
      stringArray0[2] = "x+`r[v3:%lhZ|F7N%";
      stringArray0[3] = "#<>4zzqPQ$I.";
      stringArray0[4] = "mk^8/iR6CIp:]";
      stringArray0[5] = "";
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.goodValues();
      String[] stringArray1 = new String[5];
      stringArray1[0] = "x+`r[v3:%lhZ|F7N%";
      stringArray1[1] = "#<>4zzqPQ$I.";
      stringArray1[2] = "x+`r[v3:%lhZ|F7N%";
      stringArray1[3] = "mk^8/iR6CIp:]";
      stringArray1[4] = "u!70L9";
      DisjSetsFast.main(stringArray1);
      int int0 = (-881);
      // Undeclared exception!
      try { 
        disjSetsFast0.find((-881));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(0);
      String[] stringArray0 = new String[5];
      DisjSetsFast.main(stringArray0);
      stringArray0[0] = "";
      DisjSetsFast.main(stringArray0);
      stringArray0[1] = "l-&);tJaJ;2L8XEh";
      stringArray0[2] = "gvlU'pQe@Kuy";
      stringArray0[3] = "Z5iW1pig`GaEvmKd";
      stringArray0[4] = "";
      String[] stringArray1 = new String[3];
      stringArray1[0] = "";
      stringArray1[1] = "";
      stringArray1[2] = "";
      DisjSetsFast.main(stringArray1);
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.goodValues();
      disjSetsFast0.goodValues();
      // Undeclared exception!
      try { 
        disjSetsFast0.union(0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(1035);
      String[] stringArray0 = new String[5];
      String[] stringArray1 = new String[4];
      stringArray1[0] = "";
      stringArray1[1] = "%Wq";
      stringArray1[2] = "";
      stringArray1[3] = ".";
      DisjSetsFast.main(stringArray1);
      stringArray0[0] = "";
      stringArray0[1] = "DxKSRSh";
      stringArray0[2] = "";
      stringArray0[3] = "8XSW?MF G{M*BsB\"dBJ";
      stringArray0[4] = "";
      DisjSetsFast.main(stringArray0);
      // Undeclared exception!
      try { 
        disjSetsFast0.union(1035, (-569));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(1234);
      String[] stringArray0 = new String[9];
      stringArray0[0] = "8^meC";
      stringArray0[1] = "";
      stringArray0[2] = "_hT$f2";
      stringArray0[3] = "H:]";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "/dk>=nf#f>2ha4=Sw";
      stringArray0[7] = "";
      stringArray0[8] = " ^=fUx%[";
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.find(1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(16);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.union(0, 0);
      // Undeclared exception!
      try { 
        disjSetsFast0.find((-1228));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "aW?05tn:";
      stringArray0[4] = "3T&2p!h/O21@$I9";
      DisjSetsFast.main(stringArray0);
      DisjSetsFast disjSetsFast0 = new DisjSetsFast(1);
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.acyclic();
      DisjSetsFast.main(stringArray0);
      disjSetsFast0.Find(0);
      disjSetsFast0.acyclic();
      disjSetsFast0.find(0);
      // Undeclared exception!
      try { 
        disjSetsFast0.Find(1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
