/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 08 23:08:13 GMT 2021
 */

package common;

import org.junit.Test;
import static org.junit.Assert.*;
import common.Underflow;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Underflow_ESTest extends Underflow_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Underflow underflow0 = new Underflow();
  }
}
