/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 18:19:17 GMT 2021
 */

package intkey;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import intkey.RangeTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RangeTest_ESTest extends RangeTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RangeTest rangeTest0 = null;
      try {
        rangeTest0 = new RangeTest();
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Unresolved compilation problems: 
         // \tThe import junit cannot be resolved
         // \tTestCase cannot be resolved to a type
         // \tThe method setUp() of type RangeTest must override a superclass method
         //
         verifyException("intkey.RangeTest", e);
      }
  }
}
