/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 08 23:56:25 GMT 2021
 */

package javaFiles;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import javaFiles.DoubleLinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DoubleLinkedList_ESTest extends DoubleLinkedList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = null;
      try {
        doubleLinkedList0 = new DoubleLinkedList();
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Unresolved compilation problem: 
         // \tThe declared package \"\" does not match the expected package \"javaFiles\"
         //
         verifyException("javaFiles.DoubleLinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DoubleLinkedList doubleLinkedList0 = null;
      try {
        doubleLinkedList0 = new DoubleLinkedList((Collection) null);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Unresolved compilation problem: 
         // \tThe declared package \"\" does not match the expected package \"javaFiles\"
         //
         verifyException("javaFiles.DoubleLinkedList", e);
      }
  }
}
