/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 18:20:34 GMT 2021
 */

package intkey;

import org.junit.Test;
import static org.junit.Assert.*;
import intkey.BinaryNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BinaryNode_ESTest extends BinaryNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BinaryNode binaryNode0 = new BinaryNode(0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BinaryNode binaryNode0 = new BinaryNode();
      BinaryNode binaryNode1 = new BinaryNode(0, binaryNode0, binaryNode0);
      assertFalse(binaryNode1.equals((Object)binaryNode0));
  }
}
