/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 09 18:20:32 GMT 2021
 */

package intkey;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import intkey.BinarySearchTreeTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BinarySearchTreeTest_ESTest extends BinarySearchTreeTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BinarySearchTreeTest binarySearchTreeTest0 = null;
      try {
        binarySearchTreeTest0 = new BinarySearchTreeTest();
        fail("Expecting exception: Error");
      
      } catch(Error e) {
         //
         // Unresolved compilation problems: 
         // \tThe import junit cannot be resolved
         // \tThe import edu cannot be resolved
         // \tThe import edu cannot be resolved
         // \tThe import edu cannot be resolved
         // \tTestCase cannot be resolved to a type
         // \tVerySimpleFormatter cannot be resolved to a type
         // \tUtil cannot be resolved
         // \tMethod cannot be resolved to a type
         //
         verifyException("intkey.BinarySearchTreeTest", e);
      }
  }
}
